version: '3.8'

services:
  smtp-send-only:
    build: .
    image: itx/smtp-send-only:latest
    restart: unless-stopped
    environment:
      - POSTFIX_MYDOMAIN=${POSTFIX_MYDOMAIN}
      - RELAY_HOST=${RELAY_HOST}
      - RELAY_PORT=${RELAY_PORT}
      - RELAY_USER=${RELAY_USER}
      - RELAY_PASS=${RELAY_PASS}
    ports:
      - "127.0.0.1:2525:25" # bind to localhost only by default; map 2525 to 25 locally
    volumes:
      - ./data/postfix/spool:/var/spool/postfix
      - ./data/postfix/lib:/var/lib/postfix
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
