version: '3.8'
services:
  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    environment:
      - PORT=5000
      - ENABLE_REDIS=true
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGIN=http://localhost
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 700M
  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

volumes:
  redis-data:
