version: '3.8'
services:
  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=ftuser
      - POSTGRES_PASSWORD=ftpassword
      - POSTGRES_DB=fasttap
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../deployment/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 1024M
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    env_file:
      - ../fast-tap-backend/.env
    environment:
      - PORT=5000
      - ENABLE_REDIS=true
      - REDIS_URL=redis://redis:6379
      - MAX_PLAYERS_PER_ROOM=500
      - CORS_ORIGIN=https://te-itx-2025.site
      - GAME_DURATION=3000000
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.2'
          memory: 3072M
  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.frontend
    # Published host port 8080 -> container 80 so host-level nginx (running on host:80)
    # can proxy to 127.0.0.1:8080. This avoids conflicts with host nginx listening on
    # port 80 and keeps compose services reachable from host nginx.
    ports:
      - "8080:80"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://te-itx-2025.site
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1536M
  smtp-send-only:
    build:
      context: ./smtp
    image: itx/smtp-send-only:latest
    restart: unless-stopped
    env_file:
      - ./smtp/.env      # or move vars to the root .env if you prefer
    environment:
      - POSTFIX_MYDOMAIN=${POSTFIX_MYDOMAIN:-te-itx-2025.site}
      - RELAY_HOST=${RELAY_HOST:-}
      - RELAY_PORT=${RELAY_PORT:-587}
      - RELAY_USER=${RELAY_USER:-}
      - RELAY_PASS=${RELAY_PASS:-}
    # expose port 25 to other containers (internal Docker network)
    ports:
      - "2525:25"    # optional: publish to host for debugging; remove if you don't want host binding
    volumes:
      - ./smtp/data/postfix/spool:/var/spool/postfix
      - ./smtp/data/postfix/lib:/var/lib/postfix
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  redis-data:
  postgres-data: