apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: tls-cert
              mountPath: /etc/ssl/certs/te-itx-2025.site.crt
              subPath: te-itx-2025.site.crt
            - name: tls-key
              mountPath: /etc/ssl/private/te-itx-2025.site.key
              subPath: te-itx-2025.site.key
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: tls-cert
          secret:
            secretName: te-itx-2025-tls
            items:
              - key: tls.crt
                path: te-itx-2025.site.crt
        - name: tls-key
          secret:
            secretName: te-itx-2025-tls
            items:
              - key: tls.key
                path: te-itx-2025.site.key
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      type: LoadBalancer
